### ISSUE TITLE
Problem with 174H machine starting and online reading

### ISSUE THREAD

**Issue by TracyCui339** [testo/toolbox_classic#5]
I have the same problem, This is the code:
`import win32com.client

testo_toolbox = win32com.client.Dispatch("Tcddka.tcddk")

serial_number = "37719945"
device_code = "testo174-2010"
timeout = 4000
result = testo_toolbox.InitSerial(serial_number, device_code, timeout)

if result == 1:
    print("Initialization successful")
    if testo_toolbox.NumCols > 0:
        testo_toolbox.Get
        for i in range(testo_toolbox.NumCols):
            if testo_toolbox.IsNonNumeric(i):
                msg = str(i) + " " + testo_toolbox.StringVal(i)
                print(msg)
            else:
                value = testo_toolbox.RecentVal(i)
                unit = testo_toolbox.Unit(i)
                msg = f"{i} {value:0.1f} {unit}"
                print(msg)
else:
    print("Initialization failed")`

The output is not true:
Initialization successful
0 0.0 °C
1 0.0 %rH

By the way, I got this outcome with the status "End" shown on the testo174H screen, so I tried use ”Start“ function first and then read the data, but I failed. Would you pls provide VB (or other language) code sample on how to use the start function and read the data? There's no code sample about this on 17ba.hlp. Thank you!

**Comment by FlominatorTM** [comment]
Sorry for not commenting on the other issue. You will need to replace t17b.dll with [this one](https://github.com/testo/toolbox_classic/files/13876440/t17b.zip). The customer from the other ticket had received this file already, but I forgot to put it online. We will publish a new release soon, which will include the file as well.

Access for testo 174-2010 is via the property tcddk::Instrument supplying a T17baInstrument type. You also have to add a reference to the t17ba typelib to your project. 

```
Dim tcd As tcddk
Dim Inst As T17baInstrument
Set tcd = New tcddk
bInit = tcd.InitSerial(0, "testo174-2010", 3000)
If (True = bInit) Then
Set Inst = tcd.Instrument
...
Set Inst = Nothing
tcd.Exit
End If
Set tcd = Nothing
```

T17baInstrument contains a nested object:
Program	T17baProg

Most modifications require a break in the measurement for ITxxxAProg::Save. In order to save the instrument has to be in _MOD_WAIT, _MOD_END or _MOD_TM mode. 

T17baProg has start and stop methods 

You can call Program.Start 

Later read out the memory content as seen above or explained in the documentation at hhtcde.chm.

Does this help?

**Comment by TracyCui339** [comment]
Hi, thank you for your information! Now I can successfully start and stop the sensor. However, I still cannot read the data.
```
#connect and use Instrument
tcd = win32com.client.Dispatch("tcddka.tcddk")
bInit = tcd.InitSerial("37719945", "testo174-2010", 4000)

if bInit:
    print("Initialization successful")

    inst = tcd.Instrument 
```
```
inst.Program.Start()
#wait for 5 mins
```
```
inst.Program.Stop()
```
```
inst.Program.Save()
```
Then I want to use the "Item" method to read the data.
```
inst.Program.Item(0)
```
But failed. I noticed that I can also use the "Get" and "RecentVal" method to read the data, so I set inst as "None" first, then use the RecentVal method to get the data, but it's still 0. (I also tried these before setting inst as None, also failed, there're no such methods under "Instrument")
```
b = tcd.RecentVal(1)
b
```
I also use Item method which under the "Protocols" after I set the Instrument as None, but the return is "None".
```
a = tcd.Protocols.Item(0)
a
```
Now my understanding of the sequence is : 
InitSerial → Instrument → Program.Start → Program.Stop → Program.Save → Exit Instrument (set as None) → Get → Rencent Val (or Protocols → Item)
The outcome is still 0. So I would like to inquire whether there's any problem with the sequence of methods? Thank you!

**Comment by FlominatorTM** [comment]
You are probably lacking the Get call to prot, please take a look at this sample:
```
Dim inst As tcddk
Dim bRet As Boolean
Dim prot As Protocol
On Error GoTo ErrorLabel
Set inst = New tcddk
bRet = inst.InitSerial(0, "xxx", yyy)
If True = bRet Then
If (inst.Protocols.Count > 0) Then
Set prot = inst.Protocols.Item(0)
**prot.Get**
Set prot = nothing
End if
End If
GoTo EndLabel
ErrorLabel:
MsgBox Err.Description
EndLabel:
Set inst = Nothing

```

**Comment by TracyCui339** [comment]
Hi! Thank you for your information. I tried to add Get to the code, but it is still incorrect. I tried online measurement, but the result is still 0. Then I tried to read from Protocol, and use the Protocols.Get, but it only allowed me to read one set of data each time I run the Get, and it is inconsistent with what is displayed on the 174-2010 screen. Below are the codes and results for the two methods used:
'''
#online measurement

import win32com.client

tcd = win32com.client.Dispatch("tcddka.tcddk")
bInit = tcd.InitSerial("37719945", "testo174-2010", 4000)
if bInit:
    print("Initialization successful")

inst = tcd.Instrument

inst.Program.Start()
#wait for 5 mins

inst.Program.Stop()

inst = None

tcd.numCols

# output: 2

tcd.Get
# output: True

print('Whether the Channel 0 Value is non num: ', tcd.IsNonNumeric(0))
print('Whether the Channel 1 Value is non num: ', tcd.IsNonNumeric(1))
print('Channel 0 Value by Using Val(): ',tcd.Val(0))
print('Channel 1 Value by Using Val(): ',tcd.Val(1))
print('Rencent Channel Value by Using RecentVal(): ', tcd.RecentVal(0))
print('Print String Information: ', tcd.StringVal(0))

#output: Whether the Channel 0 Value is non num:  False
#Whether the Channel 1 Value is non num:  False
#Channel 0 Value by Using Val():  0.0
#Channel 1 Value by Using Val():  0.0
#Rencent Channel Value by Using RecentVal():  0.0
#Print String Information:  
'''
Method 2 - Protocol data reading:

'''
import win32com.client

inst = win32com.client.Dispatch("tcddka.tcddk")
bRet = inst.InitSerial("37719945", "testo174-2010", 4000)

if bRet:
    for prot in inst.Protocols:
        prot.Get
        
        key = prot.NumKey
        
        print(key)
        
        a = prot.Val(0,0)
        print('Val(0,0) Value: ', a)
        
        b = prot.Val(0,1)
        print('Val(0,1) Value: ', b)

# output: 0
#             Val(0,0) Value:  29.399999618530273
#             Val(0,1) Value:  63.70000076293945
'''
For me, online measurement would be more suitable, but I don't know why the data read is still 0. Do you have any suggestions or solutions for this matter? I appreciate your assistance. Thank you!

**Comment by FlominatorTM** [comment]
Just to be sure: you replaced the DLL above, right?

**Comment by TracyCui339** [comment]
> Just to be sure: you replaced the DLL above, right?

Yes I replaced the DLL.

**Comment by FlominatorTM** [comment]
Can we please to this over email, as it might take a bit to figure out the actual problem.
Please email me via fstraub@testo.de

**Comment by FlominatorTM** [comment]
I'm sorry, I should have stated more explicitly that the DLL is supposed to be exchanged at ``C:\Program Files (x86)\Common Files\Testo Shared``
